### ISSUE TITLE
request: please support getting app and version (b0 01 00 00)

### ISSUE THREAD

**Issue by gre** [LedgerHQ/speculos#22]

**Comment by greenknot** [comment]
This APDU used to crash speculos. This is now fixed with b9d2cd393245134a4797a959e82957d9ddd96fc4, 316dbdd217f33ed4890d3909bb43e2e343183547 and  d3bdd45c6f4ca0703ab3698f6f857debd6957ed6.

The app name and version were hardcoded (`app` and `1.33.7`). df5a5433e68be0969c7a55d27a14b93abb551906 allows to set them through `SPECULOS_APPNAME` environment variable. For instance:

```bash
$ SPECULOS_APPNAME=blah:1.2.3.4 ./speculos.py ./apps/btc.elf &
$ echo 'b0 01 00 00 00' \
  | LEDGER_PROXY_ADDRESS=127.0.0.1 LEDGER_PROXY_PORT=9999 ledgerctl send - \
  | xxd -r -ps \
  | hd
00000000  01 04 62 6c 61 68 07 31  2e 32 2e 33 2e 34 01 00  |..blah.1.2.3.4..|
00000010  90 00                                             |..|
00000012
```

I'm not sure what the use case is, but if the environment variable isn't convenient, one can introduce yet another argument to `speculos.py`.
